# config.yaml
data:
  training_data_path: "data/raw/financial_regression.csv"
  test_data_path: "data/raw/financial_regression_test.csv"        #Placeholder for testing data
  output_dir: "data/saved_model/trained_model.pkl"

model:
  learning_rate: 0.001
  num_iterations: 200

split:
  test_size: 0.25
  random_state: 42
